export const TYPEORM = "TYPEORM";
export const CUSTOMER_REPOSITORY = "CUSTOMER_REPOSITORY_REPOSITORY";
export const DATABASE_CONNECTION = "DATABASE_CONNECTION"
export const REFRESHTOKEN_REPOSITORY = "REFRESHTOKEN_REPOSITORY"